version: "3.8"

services:
  # Service PHP (Symfony)
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    networks:
      - symfony_net
    depends_on:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfonydb
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "8000:8000"  # Ajout du mappage du port


  # Serveur Nginx pour Symfony
  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - symfony_net

  # Service MySQL
  mysql:
    image: mysql:5.7
    container_name: symfony_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfonydb
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - symfony_net

  # Service React (Frontend)
  react:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.react  # Vérifie que ce fichier existe
    container_name: react_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"  # Port pour Vite (hot reload)
    networks:
      - symfony_net
    depends_on:
      - php  # Optionnel si tu as besoin de communiquer avec le backend Symfony

networks:
  symfony_net:
    driver: bridge

volumes:
  mysql_data:

